name: Deploy ROM Downloader to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Create deployment directory
        run: |
          mkdir -p ./public
          
      - name: Copy frontend files to public directory
        run: |
          cp index.html ./public/
          cp styles.css ./public/
          cp app.js ./public/
          cp platforms.js ./public/
          cp README.md ./public/
          
      - name: Create demo mode indicator
        run: |
          echo '<!-- GitHub Pages Demo Mode -->' >> ./public/index.html
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
